### ISSUE TITLE
Import Transactions from a Spreadsheet

### ISSUE THREAD

**Issue by Hona** [Hona/UpBlazor#14]
Store transactions in the database

- [ ] Create a `TransactionResource` Repository

Allow importing transactions from a spreadsheet

- [ ] Work out abstracted format for the spreadsheet
- [ ] Create a parser
- [ ] Create a settings page to import from a spreadsheet - save to repository
