### ISSUE TITLE
Transactions Page

### ISSUE THREAD

**Issue by Hona** [Hona/UpBlazor#15]
View all transactions in a new page, under Insights

- [ ] Paginate the recent transactions (time span)
- [ ] add [tags](https://antblazor.com/en-US/components/tag) for Up 'Categories'/'Tags'
- [ ] Fetches and aggregates from
     - [ ]  Repository (cached from excel spreadsheet, or cached from the API?)
     - [ ]  API call - live, and paginated
