### ISSUE TITLE
Abstract Up API to some generic interface

### ISSUE THREAD

**Issue by Hona** [Hona/UpBlazor#16]
- [ ] Create generic interface for generic bank models, as separate NuGet package
- [ ] Create an aggregate generic interface, for accessing this data: `IBankApi`
- [ ] Up.NET needs to implement this generic interface
- [ ] ICurrentUserService should return `IBankApi` instead of `IUpApi`
- [ ] Refactor Blazor components to use IBankApi instead of `IUpApi`
