### ISSUE TITLE
Create Transactions Dataset Selector Component

### ISSUE THREAD

**Issue by Hona** [Hona/UpBlazor#25]
- [ ] Allow inputs from Cache (uploaded spreadsheet in repo), or API, new upload of spreadsheet, or all- [Switch](https://antblazor.com/en-US/components/switch)?
- [ ] Allow [daterange selection](https://antblazor.com/en-US/components/datepicker) 
- [ ] Show preview count of items (from all sources applicable)
- [ ] Add a preview button which shows a [drawer](https://antblazor.com/en-US/components/drawer) of the transactions
